
var infosEng = {
    lang:"eng",
    bkbMap:"MAP",
    bkbSite:"SITE",
    bkbAbout:"CONTACT",
    langpar:"Choose language: ",
    suggestp:"We also recomend: ",
    bkbm_button:["NEWS",
                 "CATERING FACILITIES",
                 "VENUES",
                 "SERVICES",
                 "EVENTS",
                 "LORE"],
    pageheader:["NEWS",
                 "CATERING FACILITIES",
                 "VENUES",
                 "SERVICES",
                 "EVENTS",
                 "LORE"],
    uparrow:"SEE NEWER NEWS",
    dwnarrow:"SEE OLDER NEWS",
    chooseTwn:"Choose Town:",
    noSVCalrt:["There are no Catering Facilities in this town",
               "There are no Venues in this town",
               "There are no Services in this town",
               "There are no lore in this town"],
    cvsBackbtn:"Choose another town",
    cvsTown_sth:" Town: ",
    bkbOclosebtn:"CLOSE",
    visitPage:"Visit personal page",
    visitText:" times seen",
    contactAbout:"We are homeloving ambitious people, whose priority is presenting our homeland in it's best light, \nas well as spreading knowledge about this paradise and all of it's potentials, if you want to take part in\npresenting our place, feel free to make CONTACT:\n\ntel: +38269570907\nmail: vukanic@gmail.com"
};
var infosRuss = {
    lang:"rus",
    bkbMap:"MAPr",
    bkbSite:"SITEr",
    bkbAbout:"CONTACTr",
    langpar:"Choose languager: ",
    suggestp:"We also recomendr: ",
    bkbm_button:["NEWSr",
                 "CATERING FACILITIESr",
                 "VENUESr",
                 "SERVICESr",
                 "EVENTSr",
                 "LOREr"],
    pageheader:["NEWSr",
                 "CATERING FACILITIESr",
                 "VENUESr",
                 "SERVICESr",
                 "EVENTSr",
                 "LOREr"],
    uparrow:"SEE NEWER NEWSr",
    dwnarrow:"SEE OLDER NEWSr",
    chooseTwn:"Choose Townr:",
    noSVCalrt:["There are no Catering Facilities in this townr",
               "There are no Venues in this townr",
               "There are no Services in this townr",
               "There are no lore in this townr"],
    cvsBackbtn:"Choose another townr",
    cvsTown_sth:" Townr: ",
    bkbOclosebtn:"CLOSEr",
    visitPage:"Visit personal pager",
    visitText:" times seenr"
};
var infosYug = {
    lang:"yug",
    bkbMap:"MAPA",
    bkbSite:"SAJT",
    bkbAbout:"KONTAKT",
    langpar:"Izaberi jezik: ",
    suggestp:"Preporučujemo: ",
    bkbm_button:["NOVOSTI",
                 "UGOSTITELJSKI OBJEKTI",
                 "MESTA ZA IZLASKE",
                 "USLUGE",
                 "DOGADJAJI",
                 "SAZNANJA"],
    pageheader:["NOVOSTI",
                 "UGOSTITELJSKI OBJEKTI",
                 "MESTA ZA IZLASKE",
                 "USLUGE",
                 "DOGADJAJI",
                 "SAZNANJA"],
    uparrow:"PRIKAŽI NOVIJE VESTI",
    dwnarrow:"PRIKAŽI STARIJE VESTI",
    chooseTwn:"Izaberi Grad:",
    noSVCalrt:["U ovom gradu nema ugostiteljskih objekata",
               "U ovom gradu nema mesta za izlaske",
               "U ovom gradu nema usluga",
               "U ovom gradu nema znanja"],
    cvsBackbtn:"Izaberi drugi grad",
    cvsTown_sth:" Grad: ",
    bkbOclosebtn:"ZATVORI",
    visitPage:"Poseti ličnu stranicu",
    visitText:" puta viđeno",
    contactAbout:"Mi smo domoljubivi ambiciozni ljudi, kojima je prioritet prikazivanje naše domovine u najljepšem svjetlu,\nkao i da što više ljudi sazna za ovaj predivni kutak svijeta i sve njegove potencijale, ako želite da\ndoprinesete prezentiranju našeg mjesta osjećajte se slobodno da nas KONTAKTIRATE:\n\ntel: +38269570907\nmail: vukanic@gmail.com"
};